name: ci

on:
  push:
    branches: ['main']

jobs:
  build:
    name: Сборка проекта
    runs-on: ubuntu-latest
    steps:
      - name: Клонирование репозитория
        uses: actions/checkout@v3
      - name: Настройка QEMU
        uses: docker/setup-qemu-action@v3
      - name: Настройка Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Авторизация в Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/elle-web:latest

  deploy:
    name: Доставка приложения
    runs-on: ubuntu-latest
    needs:
      - build

    steps:
      - name: Деплой образа
        uses: appleboy/ssh-action@master
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          host: ${{ secrets.SSH_HOSTNAME }}
          username: ${{ secrets.SSH_USERNAME }}
          passphrase: ${{secrets.SSH_PASSPHRASE}}
          script: |
            cd /home/${{ secrets.SSH_USERNAME }}/projects/elle-web && ./run.sh
